name: Publish Latest Images

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build base image
        run: |
          cd base
          docker build . -t hstreamdb/kafka-connect-base

      - name: Push images to dockerhub
        run: |
          docker push hstreamdb/kafka-connect-base
